from __future__ import annotations

from dataclasses import dataclass, field
from datetime import datetime
from pathlib import Path
from typing import Callable, Optional

from ..errors import BackupCancelled
from ..jalali import format_jalali_datetime
from .trees import _write_tree


@dataclass
class RootFileStats:
    files_written: int = 0
    files: list[Path] = field(default_factory=list)


def write_project_root_files(
    project_root: Path,
    backup_dir: Path,
    backup_dt: datetime,
    note: str,
    warn: Optional[Callable[[str], None]] = None,
    cancel_check: Optional[Callable[[], bool]] = None,
) -> RootFileStats:
    """
    Write lightweight helper files into the project root.

    Tree.md: directory tree (text, fenced for readability)
    AllCode_Backup.md: short summary pointing to the backup directory
    """
    stats = RootFileStats()
    tree_md = project_root / "Tree.md"
    tmp_tree = tree_md.with_suffix(".md.tmp")
    _write_tree(
        project_root,
        tmp_tree,
        ts_only=False,
        cancel_check=cancel_check,
    )
    # Wrap tree content in a Markdown code block and move into Tree.md
    content = tmp_tree.read_text(encoding="utf-8")
    tree_md.write_text(f"```\n{content}\n```\n", encoding="utf-8")
    tmp_tree.unlink(missing_ok=True)
    stats.files_written += 1
    stats.files.append(tree_md)

    if cancel_check and cancel_check():
        raise BackupCancelled()

    all_code = project_root / "AllCode_Backup.md"
    all_code.write_text(
        "\n".join(
            [
                "# Backup Snapshot",
                "",
                f"- Backup folder: `{backup_dir}`",
                f"- Timestamp (ISO): {backup_dt.isoformat()}",
                f"- Timestamp (Jalali): {format_jalali_datetime(backup_dt)}",
                f"- Note: {note or '-'}",
                "",
                "_Generated by TBcms Backup Studio_",
            ]
        ),
        encoding="utf-8",
    )
    stats.files_written += 1
    stats.files.append(all_code)
    return stats
